package hk.hku.cs.comp7506_project.Wiki;

import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.Bundle;

import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import hk.hku.cs.comp7506_project.R;


import androidx.appcompat.app.AppCompatActivity;

public class FinBook extends AppCompatActivity {

    private RecyclerView mRecyclerView;
    private RecyclerView.Adapter mAdapter;
    private RecyclerView.LayoutManager mLayoutManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_finbook);
        mRecyclerView = (RecyclerView) findViewById(R.id.faculty_recycle_view);
        mRecyclerView.setHasFixedSize(true);

        mLayoutManager = new GridLayoutManager(this, 2);
        mRecyclerView.setLayoutManager(mLayoutManager);


        Bitmap[] image = {
                BitmapFactory.decodeResource(getResources(), R.mipmap.booklist1),
                BitmapFactory.decodeResource(getResources(), R.mipmap.booklist2),
                BitmapFactory.decodeResource(getResources(), R.mipmap.booklist3),
                BitmapFactory.decodeResource(getResources(), R.mipmap.booklist7),
                BitmapFactory.decodeResource(getResources(), R.mipmap.booklist5),
                BitmapFactory.decodeResource(getResources(), R.mipmap.booklist6),
//                BitmapFactory.decodeResource(getResources(), R.mipmap.booklist7),
//                BitmapFactory.decodeResource(getResources(), R.mipmap.booklist8),
//                BitmapFactory.decodeResource(getResources(), R.mipmap.booklist9),
//                BitmapFactory.decodeResource(getResources(), R.mipmap.booklist10),
//                BitmapFactory.decodeResource(getResources(), R.mipmap.booklist11),

        };
        String[] names = {
                "Cash Flow", "Invoice Finance", "Cash Accounting", "Abnormal Rate Of Return","Interest","Forward rate agreement",
//                "Bottom Line","Balance Sheet","Capital","Depreciation","Assets"
        };
        String[] intro = {
                "The amount of cash or cash-equivalent which the company receives or gives out by the way of payment(s) to creditors is known as cash flow. Cash flow analysis is often used to analyse the liquidity position of the company. It gives a snapshot of the amount of cash coming into the business, from where, and amount flowing out. ",
                "Invoice financing is a form of short term borrowing which is extended by the bank or a lender to its customers based on unpaid invoices. Invoice financing is often carried out to meet short-term liquidity needs of the company. ",
                "Cash accounting is the methodology under which transactions are recorded when they actually happen. For example, income will be recorded when the company receives cash and expenses are recorded when they are actually paid out and not when the bill is raised",
                "Abnormal rate of return or ‘alpha’ is the return generated by a given stock or portfolio over a period of time which is higher than the return generated by its benchmark or the expected rate of return. It is a measure of performance on a risk-adjusted basis.",
                "Interest is payment from a borrower or deposit-taking financial institution to a lender or depositor of an amount above repayment of the principal sum (i.e., the amount borrowed), at a particular rate.",
                "A forward rate agreement's (FRA's) effective description is a cash for difference derivative contract, between two parties, benchmarked against an interest rate index. That index is commonly an interbank offered rate (-IBOR) of specific tenor in different currencies, for example LIBOR in USD, GBP, EURIBOR in EUR or STIBOR in SEK. An FRA between two counterparties requires a fixed rate, notional amount, chosen interest rate index tenor and date to be completely specified.",
//                "This is the total amount a business has earned or lost at the end of the month. The bottom line is the last financial figure on a ledger. The term can also be used in the context of a business’ earnings either increasing or decreasing.",
//                "A business’ balance sheet gives a snapshot of the company’s financial situation at a given moment. This includes the cash it has on hand, the notes payable it has outstanding and owner(s) equity in the business. Download a free balance sheet template here.",
//                "In business finance terms, the money a business has in its accounts, assets and investments is known as capital. In business, there are two major types of capital: debt and equity.",
//                "Over time, a business’ assets decrease in value due to the time that has passed since it was purchased. For tax purposes, a business can recover the cost of that depreciation through a deduction.",
//                "These are the economic resources a business has, including the products it has in inventory, the office furniture and supplies purchased for use, and any trademarks or copyrights it owns. These assets count toward the value of a business, since they could be sold if the business experienced difficult times."
        };

        mAdapter = new TermAdapter(image, names, intro);
        mRecyclerView.setAdapter(mAdapter);

    }
}




